# Generated by Django 2.2.17 on 2021-01-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210116_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='test_image',
            field=models.ImageField(default='default.jpg', upload_to='user_pics'),
        ),
    ]
